In [54]:
import numpy as np

### Задание 1

In [55]:
# а) 
    # A(4,2) и B(4,2)
        # A*B и B*A не определено, не соответствует условиям произведения матриц

In [56]:
# б) 
    # A(2,5) и B(5,3)
A = np.array([[1, 2, 3, 0, -1], [0, 3, 4, 5, 6]])
B = np.ones((5,3))
print(f'A*B: \n{np.dot(A,B)}\n')
print('B*A не определено, не соответствует условиям произведения матриц')

A*B: 
[[ 5.  5.  5.]
 [18. 18. 18.]]

B*A не определено, не соответствует условиям произведения матриц


In [57]:
# в)
    # A(8,3) и B(3,8)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, -3, 5], [5, -2, 1], [4,1,6], [7,8,4], [-3, 0, -9]])
B = np.ones((3,8))  
print(f'A*B: \n{np.dot(A,B)}\n Размерность: {np.dot(A,B).shape}')
print(f'B*A: \n{np.dot(B,A)}\n Размерность: {np.dot(B,A).shape}')


A*B: 
[[  6.   6.   6.   6.   6.   6.   6.   6.]
 [ 15.  15.  15.  15.  15.  15.  15.  15.]
 [ 24.  24.  24.  24.  24.  24.  24.  24.]
 [  2.   2.   2.   2.   2.   2.   2.   2.]
 [  4.   4.   4.   4.   4.   4.   4.   4.]
 [ 11.  11.  11.  11.  11.  11.  11.  11.]
 [ 19.  19.  19.  19.  19.  19.  19.  19.]
 [-12. -12. -12. -12. -12. -12. -12. -12.]]
 Размерность: (8, 8)
B*A: 
[[25. 19. 25.]
 [25. 19. 25.]
 [25. 19. 25.]]
 Размерность: (3, 3)


In [58]:
# г)
    # A(4,4) и B(4,4)
A = np.ones((4,4))
B = np.ones((4,4))  
print(f'A*B: \n{np.dot(A,B)}\n Размерность: {np.dot(A,B).shape}')
print(f'B*A: \n{np.dot(B,A)}\n Размерность: {np.dot(B,A).shape}')

A*B: 
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
 Размерность: (4, 4)
B*A: 
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
 Размерность: (4, 4)


### Задание 2

In [59]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Сумма A и В:\n{A + B}\n')
print(f'Произведение A и B:\n{np.dot(A,B)}\n')

Сумма A и В:
[[ 5 -3]
 [ 3  5]]

Произведение A и B:
[[  4 -11]
 [ 12  -3]]



### Задание 3

In [60]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
D = 3*A - 2*B + 4*C
print(D)

[[ 11  -5]
 [  9 -12]]


### Задание 4 

In [61]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T
print(f'A*A_T: \n{np.dot(A, A_T)}\n')
print(f'A_T*A: \n{np.dot(A_T, A)}\n')

A*A_T: 
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A_T*A: 
[[45  0]
 [ 0 14]]



## 2 часть заданий
### Задание 1

In [62]:
# а)
# sinA*sinA + cosA*cosA = 1

In [96]:
# б)
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

In [97]:
# в)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(A), 1)

0.0

### Задание 2

In [98]:
# а) det(A**2)
    # det(A**2) = 16
# б) det(AT)
    # det(A) = det(AT) = 4
# в) det(2A)
    #  det(2A) = 2**n * 4

### Задание 3

In [99]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
detA = np.linalg.det(A)
print(detA)
if detA == 0:
    print('Матрица вырожденная')
else:
    print(f'Определитель не равен нулю: {detA}')

0.0
Матрица вырожденная


### Задание 4

In [107]:
# а)
A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица: \n{A}\nРанг матрицы: {np.linalg.matrix_rank(A)}')

Матрица: 
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Ранг матрицы: 2


In [108]:
# б)
A = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'Матрица: \n{A}\nРанг матрицы: {np.linalg.matrix_rank(A)}')

Матрица: 
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 5 6]]
Ранг матрицы: 3
